input {
  tcp {
    port => 5044
    codec => json_lines  # Use json_lines codec to decode JSON logs
  }
}

filter {
  # Optional: Additional filters can be added here
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]  # Update with your Elasticsearch host
    index => "second-ms-%{+YYYY.MM.dd}"  # Index pattern
  }
}

